### ISSUE TITLE
Some feature requests and code improvements in todoapp.py

### ISSUE THREAD

**Issue by da-ksh-esh** [fineanmol/Hacktoberfest2024#7405]
### **Problems in the Code:**
**Handling Empty Input**: The current code allows adding empty tasks since there is no validation to prevent adding empty strings.
**Inefficient Task Removal Logic**: The removal logic relies on the selected index, which is fine but could result in issues if no task is selected or if the task list is empty.
**Tasks Not Saved Persistently**: The tasks are stored in memory and lost when the application is closed.
**No Confirmation for Removal**: Removing a task happens instantly, which can lead to accidental deletions without confirmation.
**Unnecessary Use of Instance Variables**: Some variables could be local instead of being instance variables if they don't need to persist across the class, like task_list.

**### Solutions:**
**Input Validation:**
Ensure that only non-empty tasks can be added.
**Task Removal Improvements:**
Add checks for whether a task is selected before trying to remove it.
Consider adding a dialog to confirm the deletion.
**Task Persistence:**
Consider adding simple file-based persistence to save the tasks.
**Confirm Removal Dialog:**
Implement a confirmation dialog to avoid accidental task removal.
**Code Cleanliness:**
Improve the structure by making some variables local where appropriate.

### **Suggested Changes:**

1. Add input validation for tasks.
2. Ensure task selection before removal.
3. Add confirmation for task removal.
4. Implement task persistence using a file (optional enhancement).
5. Clean up the code for better readability.

**Comment by fineanmol** [comment]
@da-ksh-esh Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.\nMeanwhile, if you want to work on this issue, please raise a PR, and we will review and merge it.

**Comment by da-ksh-esh** [comment]
I have star the repo :)
