### ISSUE TITLE
Hacktoberfest2024 excluded label

### ISSUE THREAD

**Issue by elic4vet** [fineanmol/Hacktoberfest2024#7614]
I have raised a pull request with my changes : https://github.com/fineanmol/Hacktoberfest2024/pull/7531

and i have already starred the repository : 

![image](https://github.com/user-attachments/assets/ada924f5-eaa5-4c7e-8bf5-827fc58678d5)

But the PR are mentioned as excluded in hacktoberfest.com
![image](https://github.com/user-attachments/assets/dd671d97-08d3-4782-baca-a710d7189803)

Can you please help me ? Thanks in advance, Eli

**Comment by fineanmol** [comment]
@elic4vet Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.\nMeanwhile, if you want to work on this issue, please raise a PR, and we will review and merge it.

**Comment by elic4vet** [comment]
Thanks for the auto message, as mentioned before, i have already starred the repo.
