### ISSUE TITLE
two sum of python

### ISSUE THREAD

**Issue by abhijit9040** [fineanmol/Hacktoberfest2024#7647]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fineanmol** [comment]
@abhijit9040 Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.\nMeanwhile, if you want to work on this issue, please raise a PR, and we will review and merge it.

**Comment by abhijit9040** [comment]
Your implementation of the two_sum function looks great! It efficiently finds two numbers that add up to the target by using a dictionary to store the complements and their indices. This approach works in linear time, O(n), since you're only traversing the list once and checking for complements in constant time.

When you run the example with nums = [2, 7, 11, 15] and target = 9, the output will be [0, 1], as expected, since 2 + 7 = 9.

Let me know if you need any further explanation or modifications!

**Comment by abhijit9040** [comment]
Your implementation of the two_sum function looks great! It efficiently finds two numbers that add up to the target by using a dictionary to store the complements and their indices. This approach works in linear time, O(n), since you're only traversing the list once and checking for complements in constant time.

When you run the example with nums = [2, 7, 11, 15] and target = 9, the output will be [0, 1], as expected, since 2 + 7 = 9.

Let me know if you need any further explanation or modifications!
