### ISSUE TITLE
improve the scroll to top icon 

### ISSUE THREAD

**Issue by ravixalgorithm** [fineanmol/Hacktoberfest2024#7742]
![Screenshot 2024-10-11 092517](https://github.com/user-attachments/assets/aa7408e7-4504-4678-8c9b-62a3b4823d6d)

here in the image we can easily see that it is not much visible, so I think I can improve it
I think the "scroll to top" icon can be designed much cleaner and good-looking

@fineanmol Please assign this to me, I will improve it and pls label it with Hacktober fest also

**Comment by fineanmol** [comment]
@ravixalgorithm Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.\nMeanwhile, if you want to work on this issue, please raise a PR, and we will review and merge it.

**Comment by ravixalgorithm** [comment]
I would love to work on it @fineanmol

**Comment by ravixalgorithm** [comment]
> @ravixalgorithm Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.\nMeanwhile, if you want to work on this issue, please raise a PR, and we will review and merge it.

Can you pls label it under hacktober fest pls

**Comment by ravixalgorithm** [comment]
@fineanmol their is some sort of problem while cloning, you should look into this

**Comment by iusverma5** [comment]
Hey @fineanmol I am interested in this issue can you please assign this issue to me.
