### ISSUE TITLE
Lap timer program to count number of laps in python.

### ISSUE THREAD

**Issue by anki-space** [fineanmol/Hacktoberfest2024#7821]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fineanmol** [comment]
@anki-space Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.\nMeanwhile, if you want to work on this issue, please raise a PR, and we will review and merge it.
