### ISSUE TITLE
reduce extra width in footer

### ISSUE THREAD

**Issue by ravixalgorithm** [fineanmol/Hacktoberfest2024#7979]
**Is your feature request related to a problem? Please describe.**
The width of the footer is a little extra thus creating a horizontal scroll bar, reducing user experience 
![issue2](https://github.com/user-attachments/assets/6109509b-f0f9-479f-b969-231281336ff6)

**Describe the solution you'd like**
I will make improvements to enhance the user experience.

**Comment by fineanmol** [comment]
@ravixalgorithm Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.\nMeanwhile, if you want to work on this issue, please raise a PR, and we will review and merge it.

**Comment by ravixalgorithm** [comment]
@fineanmol Please consider it under Hacktoberfest 2024 its a humble request
