### ISSUE TITLE
improve scroll-to-top button

### ISSUE THREAD

**Issue by ravixalgorithm** [fineanmol/Hacktoberfest2024#7980]
**Is your feature request related to a problem? Please describe.**
The scroll-to-top button is not visible in a light background
![issue](https://github.com/user-attachments/assets/8d69b63a-fc89-4b0b-9307-7fb310188cd6)

**Describe the solution you'd like**
I will improve this by changing its colour to make it visible during a light background

**Comment by fineanmol** [comment]
@ravixalgorithm Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.\nMeanwhile, if you want to work on this issue, please raise a PR, and we will review and merge it.

**Comment by Harshvardhan5703** [comment]
assign it to me.
